#################################
###          GENERAL          ###
#################################
#General IFTTT
  - alias: General IFTTT
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
      service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'



#################################
###                           ###
###     FAMILY AUTOMATIONS    ###
###                           ###
#################################

#################################
###         FAMILY ARRIVE     ###
#################################

  - alias: Guy Arrive Home
    trigger:
      platform: state
      entity_id: input_boolean.guy_wifi
      to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mode_away
      - service: script.turn_on
        entity_id: script.notify_guy
        data:
          variables:
            title: 'Welcome Home Guy'
            message: >
                    Away mode is deactivated.
                    {{ "\n" }}
                    The current temperature in the family room is {{states('sensor.temperature_158d0001573b5d')}} degrees with {{states('sensor.humidity_158d0001573b5d')}} humidty.{{ "\n" }}
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Welcome Home Guy'
            message: 'Guy Arrived'
                    
  - alias: Cathy Arrive Home
    trigger:
      platform: state
      entity_id: input_boolean.cathy_wifi
      to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mode_away
      - service: script.turn_on
        entity_id: script.notify_cathy
        data:
          variables:
            title: 'Welcome Home Cathy'
            message: >
                    Away mode is deactivated.
                    {{ "\n" }}
                    The current temperature in the family room is {{states('sensor.temperature_158d0001573b5d')}} degrees with {{states('sensor.humidity_158d0001573b5d')}} humidty.{{ "\n" }}
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Welcome Home Cathy'
            message: 'Cathy Arrived'




#################################
###                           ###
###    SECURITY AUTOMATIONS   ###
###                           ###
#################################

#################################
###      GENERAL ALERTS       ###
#################################
  - alias: Urquhart Door Bell
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00012967ff
        click_type: single
    action:
      - service: script.turn_on
        entity_id: script.notify_all
        data:
          variables:
            title: 'Home Door Bell'
            message: 'Someone is at the door!'
            
  - alias: Alarm On
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000xxxxxc2
        click_type: long_click_press
    action:
      service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: f0:b4:29:cf:a9:76
        ringtone_id: 1
        ringtone_vol: 100

  - alias: Alarm Off
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000xxxxxc2
        click_type: single
    action:
      service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: f0:b4:29:cf:a9:76

#################################
###         AWAY MODE         ###
#################################
  - alias: "Away Mode On"
    trigger:
      platform: state
      entity_id: sensor.house_occupied
      to: 'unoccupied'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mode_away
        
  - alias: "Away Mode Off"
    trigger:
      platform: state
      entity_id: sensor.house_occupied
      to: 'occupied'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mode_away



#################################
###         NIGHT MODE        ###
#################################
  - alias: Turn Night Mode On
    trigger:
      platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mode_night
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Urquhart Night Mode On'
            message: 'Testing the trigger'
        
  - alias: Turn Night Mode Off
    trigger:
      platform: state
      entity_id: sun.sun
      to: 'above_horizon'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mode_night
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Urquhart Night Mode Off'
            message: 'Testing the trigger'
            
#################################
###         SLEEP MODE        ###
#################################
  - alias: Turn Sleep Mode On
    trigger:
      platform: time
      at: '21:45:00'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mode_sleep
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Urquhart Sleep Mode On'
            message: 'Testing the trigger'
        
  - alias: Turn Sleep Mode Off
    trigger:
      platform: state
      entity_id: sun.sun
      to: 'above_horizon'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mode_sleep
      - service: script.turn_on
        entity_id: script.notify_james
        data:
          variables:
            title: 'Urquhart Sleep Mode Off'
            message: 'Testing the trigger'
            
#################################
###      RESET BUTTONS        ###
#################################

#  - alias: Reset morning at 4am
#    trigger:
#      platform: time
#      at: '04:00:00'
#    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.morning_first


