homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret API_pwd
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
  purge_keep_days: 5

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

#XIAOMI
xiaomi_aqara:
 gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key
  
# Wemo
wemo:
  static:
    - 192.168.1.4
    
# JAMES NOTIFY   


sensor: !include_dir_merge_list sensors
#scene: !include scenes.yaml       
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include_dir_merge_list switches
#input_boolean: !include input_boolean.yaml
#shell_command: !include shell_command.yaml
